# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import notes_pb2 as notes__pb2


class NoteServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.list = channel.unary_unary(
        '/NoteService/list',
        request_serializer=notes__pb2.Empty.SerializeToString,
        response_deserializer=notes__pb2.NoteList.FromString,
        )
    self.insert = channel.unary_unary(
        '/NoteService/insert',
        request_serializer=notes__pb2.Note.SerializeToString,
        response_deserializer=notes__pb2.Note.FromString,
        )
    self.delete = channel.unary_unary(
        '/NoteService/delete',
        request_serializer=notes__pb2.NoteRequestId.SerializeToString,
        response_deserializer=notes__pb2.Note.FromString,
        )


class NoteServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def list(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def insert(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def delete(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_NoteServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'list': grpc.unary_unary_rpc_method_handler(
          servicer.list,
          request_deserializer=notes__pb2.Empty.FromString,
          response_serializer=notes__pb2.NoteList.SerializeToString,
      ),
      'insert': grpc.unary_unary_rpc_method_handler(
          servicer.insert,
          request_deserializer=notes__pb2.Note.FromString,
          response_serializer=notes__pb2.Note.SerializeToString,
      ),
      'delete': grpc.unary_unary_rpc_method_handler(
          servicer.delete,
          request_deserializer=notes__pb2.NoteRequestId.FromString,
          response_serializer=notes__pb2.Note.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'NoteService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
